import unittest
from mbpp_683_code import sum_Square

class TestSumSquare(unittest.TestCase):

    def test_typical_cases(self):
        self.assertTrue(sum_Square(5))
        self.assertTrue(sum_Square(10))
        self.assertFalse(sum_Square(11))
        self.assertTrue(sum_Square(14))
        self.assertFalse(sum_Square(15))
        self.assertTrue(sum_Square(20))

    def test_edge_and_boundary_conditions(self):
        self.assertFalse(sum_Square(0))
        self.assertFalse(sum_Square(1))
        self.assertFalse(sum_Square(2))
        self.assertFalse(sum_Square(3))
        self.assertFalse(sum_Square(4))
        self.assertFalse(sum_Square(6))
        self.assertFalse(sum_Square(7))
        self.assertFalse(sum_Square(8))
        self.assertFalse(sum_Square(9))
        self.assertFalse(sum_Square(12))
        self.assertFalse(sum_Square(13))
        self.assertFalse(sum_Square(16))
        self.assertFalse(sum_Square(17))
        self.assertFalse(sum_Square(18))
        self.assertFalse(sum_Square(19))
        self.assertFalse(sum_Square(21))
        self.assertFalse(sum_Square(22))
        self.assertFalse(sum_Square(23))
        self.assertFalse(sum_Square(24))
        self.assertFalse(sum_Square(25))

    def test_corner_cases(self):
        self.assertFalse(sum_Square(26))
        self.assertFalse(sum_Square(27))
        self.assertFalse(sum_Square(28))
        self.assertFalse(sum_Square(29))
        self.assertFalse(sum_Square(30))
        self.assertFalse(sum_Square(31))
        self.assertFalse(sum_Square(32))
        self.assertFalse(sum_Square(33))
        self.assertFalse(sum_Square(34))
        self.assertFalse(sum_Square(35))
        self.assertFalse(sum_Square(36))
        self.assertFalse(sum_Square(37))
        self.assertFalse(sum_Square(38))
        self.assertFalse(sum_Square(39))
        self.assertFalse(sum_Square(40))
        self.assertFalse(sum_Square(41))
        self.assertFalse(sum_Square(42))
        self.assertFalse(sum_Square(43))
        self.assertFalse(sum_Square(44))
        self.assertFalse(sum_Square(45))
        self.assertFalse(sum_Square(46))
        self.assertFalse(sum_Square(47))
        self.assertFalse(sum_Square(48))
        self.assertFalse(sum_Square(49))
        self.assertFalse(sum_Square(50))
