import unittest
from mbpp_188_code import prod_Square

class TestProdSquare(unittest.TestCase):

    def test_typical_cases(self):
        self.assertTrue(prod_Square(4))
        self.assertTrue(prod_Square(16))
        self.assertTrue(prod_Square(64))
        self.assertTrue(prod_Square(144))

    def test_edge_and_boundary_conditions(self):
        self.assertFalse(prod_Square(0))
        self.assertFalse(prod_Square(1))
        self.assertFalse(prod_Square(2))
        self.assertFalse(prod_Square(3))
        self.assertFalse(prod_Square(5))
        self.assertFalse(prod_Square(7))
        self.assertFalse(prod_Square(8))
        self.assertFalse(prod_Square(9))
        self.assertFalse(prod_Square(10))
        self.assertFalse(prod_Square(11))
        self.assertFalse(prod_Square(12))
        self.assertFalse(prod_Square(13))
        self.assertFalse(prod_Square(15))
        self.assertFalse(prod_Square(17))
        self.assertFalse(prod_Square(18))
        self.assertFalse(prod_Square(19))
        self.assertFalse(prod_Square(20))

    def test_corner_cases(self):
        self.assertFalse(prod_Square(256))
        self.assertFalse(prod_Square(400))
        self.assertFalse(prod_Square(625))
        self.assertFalse(prod_Square(1024))
        self.assertFalse(prod_Square(1296))
        self.assertFalse(prod_Square(2000))
        self.assertFalse(prod_Square(3125))
        self.assertFalse(prod_Square(4096))
        self.assertFalse(prod_Square(5000))
        self.assertFalse(prod_Square(6561))
        self.assertFalse(prod_Square(7776))
        self.assertFalse(prod_Square(8000))
        self.assertFalse(prod_Square(9216))
        self.assertFalse(prod_Square(10000))
        self.assertFalse(prod_Square(10625))
        self.assertFalse(prod_Square(11232))
        self.assertFalse(prod_Square(12500))
        self.assertFalse(prod_Square(13312))
        self.assertFalse(prod_Square(14400))
        self.assertFalse(prod_Square(15625))
        self.assertFalse(prod_Square(16000))
        self.assertFalse(prod_Square(17640))
        self.assertFalse(prod_Square(18496))
        self.assertFalse(prod_Square(20000))
        self.assertFalse(prod_Square(21870))
        self.assertFalse(prod_Square(22500))
        self.assertFalse(prod_Square(24336))
        self.assertFalse(prod_Square(25000))
        self.assertFalse(prod_Square(27000))
        self.assertFalse(prod_Square(28561))
        self.assertFalse(prod_Square(30000))
        self.assertFalse(prod_Square(32805))
        self.assertFalse(prod_Square(33750))
        self.assertFalse(prod_Square(36000))
        self.assertFalse(prod_Square(39304))
        self.assertFalse(prod_Square(40000))
        self.assertFalse(prod_Square(43264))
        self.assertFalse(prod_Square(45000))
        self.assertFalse(prod_Square(46656))
        self.assertFalse(prod_Square(50000))
        self.assertFalse(prod_Square(56250))
        self.assertFalse(prod_Square(57124))
        self.assertFalse(prod_Square(60000))
        self.assertFalse(prod_Square(65610))
        self