import unittest
from mbpp_830_code import round_up

class TestRoundUp(unittest.TestCase):

    def test_round_up(self):
        self.assertEqual(round_up(1.2, 1), 1.2)
        self.assertEqual(round_up(1.5, 1), 2.0)
        self.assertEqual(round_up(1.8, 1), 2.0)
        self.assertEqual(round_up(1.9, 1), 2.0)
        self.assertEqual(round_up(2.0, 1), 2.0)
        self.assertEqual(round_up(2.1, 1), 2.0)
        self.assertEqual(round_up(2.2, 1), 2.0)
        self.assertEqual(round_up(2.3, 1), 2.0)
        self.assertEqual(round_up(2.4, 1), 2.0)
        self.assertEqual(round_up(2.5, 1), 2.0)
        self.assertEqual(round_up(2.6, 1), 2.0)
        self.assertEqual(round_up(2.7, 1), 2.0)
        self.assertEqual(round_up(2.8, 1), 2.0)
        self.assertEqual(round_up(2.9, 1), 2.0)
        self.assertEqual(round_up(3.0, 1), 3.0)
        self.assertEqual(round_up(3.1, 1), 3.0)
        self.assertEqual(round_up(3.2, 1), 3.0)
        self.assertEqual(round_up(3.3, 1), 3.0)
        self.assertEqual(round_up(3.4, 1), 3.0)
        self.assertEqual(round_up(3.5, 1), 3.0)
        self.assertEqual(round_up(3.6, 1), 3.0)
        self.assertEqual(round_up(3.7, 1), 3.0)
        self.assertEqual(round_up(3.8, 1), 3.0)
        self.assertEqual(round_up(3.9, 1), 3.0)
        self.assertEqual(round_up(4.0, 1), 4.0)
        self.assertEqual(round_up(4.1, 1), 4.0)
        self.assertEqual(round_up(4.2, 1), 4.0)
        self.assertEqual(round_up(4.3, 1), 4.0)
        self.assertEqual(round_up(4.4, 1), 4.0)
        self.assertEqual(round_up(4.5, 1), 4.0)
        self.assertEqual(round_up(4.6, 1), 4.0)
        self.assertEqual(round_up(4.7, 1), 4.0)
        self.assertEqual(round_up(4.8, 1), 4.0)
        self.assertEqual(round_up(4.9, 1), 4.0)
        self.assertEqual(round_up(5.0, 1), 5.0)
        self.assertEqual(round_up(5.1, 1), 5.0)
        self.assertEqual(round_up(5.2, 1), 5.0)
        self.assertEqual(round_up(5.3, 1), 5.0)
        self.assertEqual(round_up(5.4, 1), 5.0)
        self.assertEqual(round_up(5.5, 1), 5.0)
        self.assertEqual(round_up(5.6, 1), 5.0)
        self.assertEqual(round_up(5.7, 1), 5.0)
        self.assertEqual(round_up(5.8, 1), 5.0)
        self.assertEqual(round_up(5.9, 1), 5.0)
        self.assertEqual(round_up(6.0, 1), 6.0)
        self.assertEqual(round_up(6.1, 1), 6.0)
        self.assertEqual(round_up(6.2, 1), 6.0)
        self.assertEqual(round_up(6.3, 1), 6.0)
        self.assertEqual(round_up(6.4, 1), 6.0)
        self.assertEqual(round_up(6.5, 1), 6.0)
        self.assertEqual(round_up(6.6, 1), 6.0)
        self.assertEqual(round_up(6.7, 1), 6.0)
        self.assertEqual(round_up(6.8, 1), 6.0)
        self.assertEqual(round_up(6.9, 1), 6.0)
        self.assertEqual(round_up(7.0, 1), 7.0)
        self.assertEqual(round_up(7