import unittest
from mbpp_506_code import permutation_coefficient

class TestPermutationCoefficient(unittest.TestCase):

    def test_permutation_coefficient(self):
        self.assertEqual(permutation_coefficient(3, 2), 3)
        self.assertEqual(permutation_coefficient(5, 3), 10)
        self.assertEqual(permutation_coefficient(10, 5), 252)
        self.assertEqual(permutation_coefficient(20, 10), 184756)
        self.assertEqual(permutation_coefficient(1, 1), 1)
        self.assertEqual(permutation_coefficient(0, 0), 1)
        self.assertEqual(permutation_coefficient(1, 0), 1)
        self.assertEqual(permutation_coefficient(0, 1), 0)
        self.assertEqual(permutation_coefficient(1, 2), 1)
        self.assertEqual(permutation_coefficient(2, 1), 2)
        self.assertEqual(permutation_coefficient(2, 2), 1)
        self.assertEqual(permutation_coefficient(3, 1), 3)
        self.assertEqual(permutation_coefficient(3, 3), 1)
        self.assertEqual(permutation_coefficient(4, 2), 6)
        self.assertEqual(permutation_coefficient(4, 4), 1)
        self.assertEqual(permutation_coefficient(5, 1), 5)
        self.assertEqual(permutation_coefficient(5, 5), 1)
        self.assertEqual(permutation_coefficient(6, 3), 20)
        self.assertEqual(permutation_coefficient(6, 6), 1)
        self.assertEqual(permutation_coefficient(7, 3), 35)
        self.assertEqual(permutation_coefficient(7, 7), 1)
        self.assertEqual(permutation_coefficient(8, 4), 70)
        self.assertEqual(permutation_coefficient(8, 8), 1)
        self.assertEqual(permutation_coefficient(9, 5), 126)
        self.assertEqual(permutation_coefficient(9, 9), 1)
        self.assertEqual(permutation_coefficient(10, 6), 210)
        self.assertEqual(permutation_coefficient(10, 10), 1)
        self.assertEqual(permutation_coefficient(11, 6), 462)
        self.assertEqual(permutation_coefficient(11, 11), 1)
        self.assertEqual(permutation_coefficient(12, 7), 924)
        self.assertEqual(permutation_coefficient(12, 12), 1)
        self.assertEqual(permutation_coefficient(13, 8), 3432)
        self.assertEqual(permutation_coefficient(13, 13), 1)
        self.assertEqual(permutation_coefficient(14, 9), 8856)
        self.assertEqual(permutation_coefficient(14, 14), 1)
        self.assertEqual(permutation_coefficient(15, 10), 24310)
        self.assertEqual(permutation_coefficient(15, 15), 1)
        self.assertEqual(permutation_coefficient(16, 11), 65520)
        self.assertEqual(permutation_coefficient(16, 16), 1)
        self.assertEqual(permutation_coefficient(17, 12), 183056)
        self.assertEqual(permutation_coefficient(17, 17), 1)
        self.assertEqual(permutation_coefficient(18, 13), 48620)
        self.assertEqual(permutation_coefficient(18, 18), 1)
        self.assertEqual(permutation_coefficient(19, 14), 121645)
        self.assertEqual(permutation_coefficient(19, 19), 1)
        self.assertEqual(permutation_coefficient(20, 15), 344160)
        self.assertEqual(permutation_coefficient(20, 20), 1)
        self.assertEqual(permutation_coefficient(21, 16), 922746)
        self.assertEqual(permutation_coefficient(21, 21), 1)
        self.assertEqual(permutation_coefficient(22, 17), 243290)
        self.assertEqual(permutation_coefficient(22, 22), 1)
        self.assertEqual(permutation_coefficient(23, 18), 618803)
        self.assertEqual(permutation_coefficient(23, 23), 1)
        self.assertEqual(permutation_coefficient(24, 19), 1679606)
        self.assertEqual(permutation_coefficient(24, 24), 1)
        self.assertEqual(permutation_coefficient(25, 20), 4368900)
        self.assertEqual(permutation_coefficient(25, 25), 1)
        self.assertEqual(permutation_coefficient(26, 21), 11879600)
        self.assertEqual(permutation_coefficient(26, 26), 1)
        self.assertEqual(permutation_coefficient(27, 22), 32535140)
        self.assertEqual(permutation_coefficient(27, 27),