import unittest
from mbpp_146_code import ascii_value_string

class TestAsciiValueString(unittest.TestCase):

    def test_ascii_value_string(self):
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("A"), 65)
        self.assertEqual(ascii_value_string("1"), 49)
        self.assertEqual(ascii_value_string("0"), 48)
        self.assertEqual(ascii_value_string(" "), 32)
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("z"), 122)
        self.assertEqual(ascii_value_string("Z"), 90)
        self.assertEqual(ascii_value_string("9"), 57)
        self.assertEqual(ascii_value_string("8"), 56)
        self.assertEqual(ascii_value_string("7"), 55)
        self.assertEqual(ascii_value_string("6"), 54)
        self.assertEqual(ascii_value_string("5"), 53)
        self.assertEqual(ascii_value_string("4"), 52)
        self.assertEqual(ascii_value_string("3"), 51)
        self.assertEqual(ascii_value_string("2"), 50)
        self.assertEqual(ascii_value_string("1"), 49)
        self.assertEqual(ascii_value_string("0"), 48)
        self.assertEqual(ascii_value_string(" "), 32)
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("z"), 122)
        self.assertEqual(ascii_value_string("Z"), 90)
        self.assertEqual(ascii_value_string("9"), 57)
        self.assertEqual(ascii_value_string("8"), 56)
        self.assertEqual(ascii_value_string("7"), 55)
        self.assertEqual(ascii_value_string("6"), 54)
        self.assertEqual(ascii_value_string("5"), 53)
        self.assertEqual(ascii_value_string("4"), 52)
        self.assertEqual(ascii_value_string("3"), 51)
        self.assertEqual(ascii_value_string("2"), 50)
        self.assertEqual(ascii_value_string("1"), 49)
        self.assertEqual(ascii_value_string("0"), 48)
        self.assertEqual(ascii_value_string(" "), 32)
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("z"), 122)
        self.assertEqual(ascii_value_string("Z"), 90)
        self.assertEqual(ascii_value_string("9"), 57)
        self.assertEqual(ascii_value_string("8"), 56)
        self.assertEqual(ascii_value_string("7"), 55)
        self.assertEqual(ascii_value_string("6"), 54)
        self.assertEqual(ascii_value_string("5"), 53)
        self.assertEqual(ascii_value_string("4"), 52)
        self.assertEqual(ascii_value_string("3"), 51)
        self.assertEqual(ascii_value_string("2"), 50)
        self.assertEqual(ascii_value_string("1"), 49)
        self.assertEqual(ascii_value_string("0"), 48)
        self.assertEqual(ascii_value_string(" "), 32)
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("z"), 122)
        self.assertEqual(ascii_value_string("Z"), 90)
        self.assertEqual(ascii_value_string("9"), 57)
        self.assertEqual(ascii_value_string("8"), 56)
        self.assertEqual(ascii_value_string("7"), 55)
        self.assertEqual(ascii_value_string("6"), 54)
        self.assertEqual(ascii_value_string("5"), 53)
        self.assertEqual(ascii_value_string("4"), 52)
        self.assertEqual(ascii_value_string("3"), 51)
        self.assertEqual(ascii_value_string("2"), 50)
        self.assertEqual(ascii_value_string("1"), 49)
        self.assertEqual(ascii_value_string("0"), 48)
        self.assertEqual(ascii_value_string(" "), 32)
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("z"), 122)
        self.assertEqual(ascii_value_string("Z"), 90)
        self.assertEqual(ascii_value_string("9"), 57)
        self.assertEqual(ascii_value_string("8"), 56)
        self.assertEqual(ascii_value_string("7"), 55)
        self.assertEqual(ascii_value_string("6"), 54)
        self.assertEqual(ascii_value_string("5"), 53)
        self.assertEqual(ascii_value_string("4"), 52)
        self.assertEqual(ascii_value_string("3"), 51)
        self.assertEqual(ascii_value_string("2"), 50)
        self.assertEqual(ascii_value_string("1"), 49)
        self.assertEqual(ascii_value_string("0"), 48)
        self.assertEqual(ascii_value_string(" "), 32)
        self.assertEqual(ascii_value_string("a"), 97)
        self.assertEqual(ascii_value_string("z"), 122