import unittest
from mbpp_772_code import remove_length

class TestRemoveLength(unittest.TestCase):

    def test_remove_length(self):
        self.assertEqual(remove_length("Hello World", 5), "Hello World")
        self.assertEqual(remove_length("Hello World", 3), "Hello World")
        self.assertEqual(remove_length("Hello World", 11), "Hello")
        self.assertEqual(remove_length("Hello World", 6), "Hello World")
        self.assertEqual(remove_length("Hello World", 7), "Hello World")
        self.assertEqual(remove_length("Hello World", 8), "Hello World")
        self.assertEqual(remove_length("Hello World", 9), "Hello World")
        self.assertEqual(remove_length("Hello World", 10), "Hello World")
        self.assertEqual(remove_length("Hello World", 12), "Hello")
        self.assertEqual(remove_length("Hello World", 13), "Hello")
        self.assertEqual(remove_length("Hello World", 14), "Hello")
        self.assertEqual(remove_length("Hello World", 15), "Hello")
        self.assertEqual(remove_length("Hello World", 16), "Hello")
        self.assertEqual(remove_length("Hello World", 17), "Hello")
        self.assertEqual(remove_length("Hello World", 18), "Hello")
        self.assertEqual(remove_length("Hello World", 19), "Hello")
        self.assertEqual(remove_length("Hello World", 20), "Hello")
        self.assertEqual(remove_length("Hello World", 21), "Hello")
        self.assertEqual(remove_length("Hello World", 22), "Hello")
        self.assertEqual(remove_length("Hello World", 23), "Hello")
        self.assertEqual(remove_length("Hello World", 24), "Hello")
        self.assertEqual(remove_length("Hello World", 25), "Hello")
        self.assertEqual(remove_length("Hello World", 26), "Hello")
        self.assertEqual(remove_length("Hello World", 27), "Hello")
        self.assertEqual(remove_length("Hello World", 28), "Hello")
        self.assertEqual(remove_length("Hello World", 29), "Hello")
        self.assertEqual(remove_length("Hello World", 30), "Hello")
        self.assertEqual(remove_length("Hello World", 31), "Hello")
        self.assertEqual(remove_length("Hello World", 32), "Hello")
        self.assertEqual(remove_length("Hello World", 33), "Hello")
        self.assertEqual(remove_length("Hello World", 34), "Hello")
        self.assertEqual(remove_length("Hello World", 35), "Hello")
        self.assertEqual(remove_length("Hello World", 36), "Hello")
        self.assertEqual(remove_length("Hello World", 37), "Hello")
        self.assertEqual(remove_length("Hello World", 38), "Hello")
        self.assertEqual(remove_length("Hello World", 39), "Hello")
        self.assertEqual(remove_length("Hello World", 40), "Hello")
        self.assertEqual(remove_length("Hello World", 41), "Hello")
        self.assertEqual(remove_length("Hello World", 42), "Hello")
        self.assertEqual(remove_length("Hello World", 43), "Hello")
        self.assertEqual(remove_length("Hello World", 44), "Hello")
        self.assertEqual(remove_length("Hello World", 45), "Hello")
        self.assertEqual(remove_length("Hello World", 46), "Hello")
        self.assertEqual(remove_length("Hello World", 47), "Hello")
        self.assertEqual(remove_length("Hello World", 48), "Hello")
        self.assertEqual(remove_length("Hello World", 49), "Hello")
        self.assertEqual(remove_length("Hello World", 50), "Hello")
        self.assertEqual(remove_length("Hello World", 51), "Hello")
        self.assertEqual(remove_length("Hello World", 52), "Hello")
        self.assertEqual(remove_length("Hello World", 53), "Hello")
        self.assertEqual(remove_length("Hello World", 54), "Hello")
        self.assertEqual(remove_length("Hello World", 55), "Hello")
        self.assertEqual(remove_length("Hello World", 56), "Hello")
        self.assertEqual(remove_length("Hello World", 57), "Hello")
        self.assertEqual(remove_length("Hello World", 58), "Hello")
        self.assertEqual(remove_length("Hello World", 59), "Hello")
        self.assertEqual(remove_length("Hello World", 60), "Hello")
        self.assertEqual(remove_length("Hello World", 61), "Hello")
        self.assertEqual(remove_length("Hello World", 62), "Hello")
        self.assertEqual(remove_length("Hello World", 63), "Hello")
        self.assertEqual(remove_length("Hello World", 64), "Hello")
        self.assertEqual(remove_length("Hello World", 65), "Hello")
        self.assertEqual(remove_length("Hello World", 66), "Hello")
        self.assertEqual(remove_length("Hello World", 67), "Hello")
        self.assertEqual(remove_length("Hello World", 68), "Hello")
        self.assertEqual(remove_length("Hello World", 69), "Hello")