import unittest
from mbpp_28_code import binomial_Coeff

class TestBinomialCoeff(unittest.TestCase):

    def test_binomial_coeff(self):
        self.assertEqual(binomial_Coeff(0, 0), 1)
        self.assertEqual(binomial_Coeff(1, 0), 1)
        self.assertEqual(binomial_Coeff(1, 1), 1)
        self.assertEqual(binomial_Coeff(2, 0), 1)
        self.assertEqual(binomial_Coeff(2, 1), 2)
        self.assertEqual(binomial_Coeff(2, 2), 1)
        self.assertEqual(binomial_Coeff(3, 0), 1)
        self.assertEqual(binomial_Coeff(3, 1), 3)
        self.assertEqual(binomial_Coeff(3, 2), 3)
        self.assertEqual(binomial_Coeff(3, 3), 1)
        self.assertEqual(binomial_Coeff(4, 0), 1)
        self.assertEqual(binomial_Coeff(4, 1), 4)
        self.assertEqual(binomial_Coeff(4, 2), 6)
        self.assertEqual(binomial_Coeff(4, 3), 4)
        self.assertEqual(binomial_Coeff(4, 4), 1)
        self.assertEqual(binomial_Coeff(5, 0), 1)
        self.assertEqual(binomial_Coeff(5, 1), 5)
        self.assertEqual(binomial_Coeff(5, 2), 10)
        self.assertEqual(binomial_Coeff(5, 3), 10)
        self.assertEqual(binomial_Coeff(5, 4), 5)
        self.assertEqual(binomial_Coeff(5, 5), 1)
        self.assertEqual(binomial_Coeff(6, 0), 1)
        self.assertEqual(binomial_Coeff(6, 1), 6)
        self.assertEqual(binomial_Coeff(6, 2), 15)
        self.assertEqual(binomial_Coeff(6, 3), 15)
        self.assertEqual(binomial_Coeff(6, 4), 6)
        self.assertEqual(binomial_Coeff(6, 5), 6)
        self.assertEqual(binomial_Coeff(6, 6), 1)
        self.assertEqual(binomial_Coeff(7, 0), 1)
        self.assertEqual(binomial_Coeff(7, 1), 7)
        self.assertEqual(binomial_Coeff(7, 2), 21)
        self.assertEqual(binomial_Coeff(7, 3), 21)
        self.assertEqual(binomial_Coeff(7, 4), 7)
        self.assertEqual(binomial_Coeff(7, 5), 7)
        self.assertEqual(binomial_Coeff(7, 6), 3)
        self.assertEqual(binomial_Coeff(7, 7), 1)
        self.assertEqual(binomial_Coeff(8, 0), 1)
        self.assertEqual(binomial_Coeff(8, 1), 8)
        self.assertEqual(binomial_Coeff(8, 2), 28)
        self.assertEqual(binomial_Coeff(8, 3), 28)
        self.assertEqual(binomial_Coeff(8, 4), 8)
        self.assertEqual(binomial_Coeff(8, 5), 8)
        self.assertEqual(binomial_Coeff(8, 6), 7)
        self.assertEqual(binomial_Coeff(8, 7), 6)
        self.assertEqual(binomial_Coeff(8, 8), 1)
        self.assertEqual(binomial_Coeff(9, 0), 1)
        self.assertEqual(binomial_Coeff(9, 1), 9)
        self.assertEqual(binomial_Coeff(9, 2), 36)
        self.assertEqual(binomial_Coeff(9, 3), 36)
        self.assertEqual(binomial_Coeff(9, 4), 9)
        self.assertEqual(binomial_Coeff(9, 5), 9)
        self.assertEqual(binomial_Coeff(9, 6), 8)
        self.assertEqual(binomial_Coeff(9, 7), 7)
        self.assertEqual(binomial_Coeff(9, 8), 6)
        self.assertEqual(binomial_Coeff(9, 9), 1)
        self.assertEqual(binomial_Coeff(10, 0), 1)
        self.assertEqual(binomial_Coeff(10, 1), 10)
        self.assertEqual(binomial_Coeff(10, 2), 45)
        self.assertEqual(binomial_Coeff(10, 3), 45)
        self.assertEqual(binomial_Coeff(10, 4), 10)
        self.assertEqual(binomial_Coeff(10, 5), 10)
        self.assertEqual(binomial_Coeff(10, 6), 9)