import unittest
from mbpp_173_code import remove_splchar

class TestRemoveSplchar(unittest.TestCase):

    def test_remove_splchar(self):
        self.assertEqual(remove_splchar("Hello, World!"), "Hello World")
        self.assertEqual(remove_splchar("Hello_World"), "HelloWorld")
        self.assertEqual(remove_splchar("Hello World!"), "Hello World")
        self.assertEqual(remove_splchar("Hello"), "Hello")
        self.assertEqual(remove_splchar("123"), "123")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World")
        self.assertEqual(remove_splchar("Hello World!@#"), "Hello World