import unittest
from mbpp_923_code import super_seq

class TestSuperSeq(unittest.TestCase):

    def test_super_seq(self):
        self.assertEqual(super_seq("abc", "def", 3, 3), 3)
        self.assertEqual(super_seq("abc", "def", 3, 2), 2)
        self.assertEqual(super_seq("abc", "def", 2, 3), 2)
        self.assertEqual(super_seq("abc", "def", 1, 1), 1)
        self.assertEqual(super_seq("abc", "def", 0, 3), 3)
        self.assertEqual(super_seq("abc", "def", 3, 0), 3)
        self.assertEqual(super_seq("abc", "def", 0, 0), 0)
        self.assertEqual(super_seq("abc", "def", 1, 0), 1)
        self.assertEqual(super_seq("abc", "def", 0, 1), 1)
        self.assertEqual(super_seq("abc", "def", 2, 2), 2)
        self.assertEqual(super_seq("abc", "def", 1, 2), 2)
        self.assertEqual(super_seq("abc", "def", 2, 1), 2)
        self.assertEqual(super_seq("abc", "def", 1, 1), 1)
        self.assertEqual(super_seq("abc", "def", 3, 3), 3)
        self.assertEqual(super_seq("abc", "def", 3, 4), 4)
        self.assertEqual(super_seq("abc", "def", 4, 3), 4)
        self.assertEqual(super_seq("abc", "def", 4, 4), 4)
        self.assertEqual(super_seq("abc", "def", 1, 4), 4)
        self.assertEqual(super_seq("abc", "def", 4, 1), 4)
        self.assertEqual(super_seq("abc", "def", 1, 5), 5)
        self.assertEqual(super_seq("abc", "def", 5, 1), 5)
        self.assertEqual(super_seq("abc", "def", 5, 5), 5)
        self.assertEqual(super_seq("abc", "def", 5, 6), 6)
        self.assertEqual(super_seq("abc", "def", 6, 5), 6)
        self.assertEqual(super_seq("abc", "def", 6, 6), 6)
        self.assertEqual(super_seq("abc", "def", 6, 7), 7)
        self.assertEqual(super_seq("abc", "def", 7, 6), 7)
        self.assertEqual(super_seq("abc", "def", 7, 7), 7)
        self.assertEqual(super_seq("abc", "def", 7, 8), 8)
        self.assertEqual(super_seq("abc", "def", 8, 7), 8)
        self.assertEqual(super_seq("abc", "def", 8, 8), 8)
        self.assertEqual(super_seq("abc", "def", 8, 9), 9)
        self.assertEqual(super_seq("abc", "def", 9, 8), 9)
        self.assertEqual(super_seq("abc", "def", 9, 9), 9)
        self.assertEqual(super_seq("abc", "def", 9, 10), 10)
        self.assertEqual(super_seq("abc", "def", 10, 9), 10)
        self.assertEqual(super_seq("abc", "def", 10, 10), 10)
        self.assertEqual(super_seq("abc", "def", 10, 11), 11)
        self.assertEqual(super_seq("abc", "def", 11, 10), 11)
        self.assertEqual(super_seq("abc", "def", 11, 11), 11)
        self.assertEqual(super_seq("abc", "def", 11, 12), 12)
        self.assertEqual(super_seq("abc", "def", 12, 11), 12)
        self.assertEqual(super_seq("abc", "def", 12, 12), 12)
        self.assertEqual(super_seq("abc", "def", 12, 13), 13)
        self.assertEqual(super_seq("abc", "def", 13, 12), 13)
        self.assertEqual(super_seq("abc", "def", 13, 13), 13)
        self.assertEqual(super_seq("abc", "def", 13, 14), 14)
        self.assertEqual(super_seq("abc", "def", 14, 13), 14)
        self.assertEqual(super_seq("abc", "def", 14, 14), 14)
        self.assertEqual(super_seq("abc", "def", 14, 15),