import unittest
from mbpp_375_code import round_num

class TestRoundNum(unittest.TestCase):

    def test_round_num(self):
        self.assertEqual(round_num(1, 1), 1)
        self.assertEqual(round_num(2, 1), 2)
        self.assertEqual(round_num(3, 1), 3)
        self.assertEqual(round_num(4, 1), 4)
        self.assertEqual(round_num(5, 1), 5)
        self.assertEqual(round_num(6, 1), 6)
        self.assertEqual(round_num(7, 1), 7)
        self.assertEqual(round_num(8, 1), 8)
        self.assertEqual(round_num(9, 1), 9)
        self.assertEqual(round_num(10, 1), 10)
        self.assertEqual(round_num(11, 1), 11)
        self.assertEqual(round_num(12, 1), 12)
        self.assertEqual(round_num(13, 1), 13)
        self.assertEqual(round_num(14, 1), 14)
        self.assertEqual(round_num(15, 1), 15)
        self.assertEqual(round_num(16, 1), 16)
        self.assertEqual(round_num(17, 1), 17)
        self.assertEqual(round_num(18, 1), 18)
        self.assertEqual(round_num(19, 1), 19)
        self.assertEqual(round_num(20, 1), 20)
        self.assertEqual(round_num(21, 1), 21)
        self.assertEqual(round_num(22, 1), 22)
        self.assertEqual(round_num(23, 1), 23)
        self.assertEqual(round_num(24, 1), 24)
        self.assertEqual(round_num(25, 1), 25)
        self.assertEqual(round_num(26, 1), 26)
        self.assertEqual(round_num(27, 1), 27)
        self.assertEqual(round_num(28, 1), 28)
        self.assertEqual(round_num(29, 1), 29)
        self.assertEqual(round_num(30, 1), 30)
        self.assertEqual(round_num(31, 1), 31)
        self.assertEqual(round_num(32, 1), 32)
        self.assertEqual(round_num(33, 1), 33)
        self.assertEqual(round_num(34, 1), 34)
        self.assertEqual(round_num(35, 1), 35)
        self.assertEqual(round_num(36, 1), 36)
        self.assertEqual(round_num(37, 1), 37)
        self.assertEqual(round_num(38, 1), 38)
        self.assertEqual(round_num(39, 1), 39)
        self.assertEqual(round_num(40, 1), 40)
        self.assertEqual(round_num(41, 1), 41)
        self.assertEqual(round_num(42, 1), 42)
        self.assertEqual(round_num(43, 1), 43)
        self.assertEqual(round_num(44, 1), 44)
        self.assertEqual(round_num(45, 1), 45)
        self.assertEqual(round_num(46, 1), 46)
        self.assertEqual(round_num(47, 1), 47)
        self.assertEqual(round_num(48, 1), 48)
        self.assertEqual(round_num(49, 1), 49)
        self.assertEqual(round_num(50, 1), 50)
        self.assertEqual(round_num(51, 1), 51)
        self.assertEqual(round_num(52, 1), 52)
        self.assertEqual(round_num(53, 1), 53)
        self.assertEqual(round_num(54, 1), 54)
        self.assertEqual(round_num(55, 1), 55)
        self.assertEqual(round_num(56, 1), 56)
        self.assertEqual(round_num(57, 1), 57)
        self.assertEqual(round_num(58, 1), 58)
        self.assertEqual(round_num(59, 1), 59)
        self.assertEqual(round_num(60, 1), 60)
        self.assertEqual(round_num(61, 1), 61)
        self.assertEqual(round_num(62, 1), 62)
        self.assertEqual(round_num(63, 1), 63)
        self.assertEqual(round_num(64, 1), 64)
        self.assertEqual(round_num(65, 1), 65)
        self.assertEqual(round_num(66, 1), 66)
        self.assertEqual(round_num(67, 1), 67)
        self.assertEqual(round_num(68, 1), 68)
        self.assertEqual(round_num(69, 1), 69)
        self.assertEqual(round_num(70, 1), 70)
        self.assertEqual(round_num(71, 1), 71)
        self.assertEqual