import unittest
from mbpp_377_code import remove_Char

class TestRemoveChar(unittest.TestCase):

    def test_remove_Char(self):
        self.assertEqual(remove_Char("Hello, World!", ","), "Hello World')
        self.assertEqual(remove_Char("Hello, World!", "o"), 'Hll, Wrld!')
        self.assertEqual(remove_Char("Hello, World!", "H"), 'ello, World!')
        self.assertEqual(remove_Char("Hello, World!", "W"), 'Hello, orld!')
        self.assertEqual(remove_Char("Hello, World!", "l"), 'Heo, o rld!')
        self.assertEqual(remove_Char("Hello, World!", "r"), 'Heo, o ld!')
        self.assertEqual(remove_Char("Hello, World!", "d"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "a"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "z"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "x"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "y"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "b"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "c"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "e"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "f"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "g"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "h"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "i"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "j"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "k"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "m"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "n"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "o"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "p"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "q"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "s"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "t"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "u"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "v"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "w"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "x"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "y"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "z"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", " "), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "H"), 'ello, World!')
        self.assertEqual(remove_Char("Hello, World!", "e"), 'Hll, Wrld!')
        self.assertEqual(remove_Char("Hello, World!", "o"), 'Hll, Wrld!')
        self.assertEqual(remove_Char("Hello, World!", "W"), 'ello, rld!')
        self.assertEqual(remove_Char("Hello, World!", "r"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "d"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "a"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "z"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "x"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "y"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "b"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "c"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "e"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "f"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "g"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello, World!", "h"), 'Heo, o l!')
        self.assertEqual(remove_Char("Hello