import unittest
from mbpp_812_code import road_rd

class TestRoadRd(unittest.TestCase):

    def test_road_rd(self):
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'), '123 Main Rd.')
        self.assertEqual(road_rd('456 Elm Street'), '456 Elm Street')
        self.assertEqual(road_rd('789 Oak Road'), '789 Oak Rd.')
        self.assertEqual(road_rd('abc Def Road'), 'abc Def Rd.')
        self.assertEqual(road_rd('xyz Ghi Road'), 'xyz Ghi Rd.')
        self.assertEqual(road_rd('123 Main Road'),