import unittest
from mbpp_11_code import remove_Occ

class TestRemoveOcc(unittest.TestCase):

    def test_remove_Occ(self):
        self.assertEqual(remove_Occ("Hello, Occ", "O"), "Hell, cc")
        self.assertEqual(remove_Occ("Hello, Occ", "o"), "Hell, cc")
        self.assertEqual(remove_Occ("Hello, Occ", "h"), "ello, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "H"), "ello, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "l"), "Heo, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "L"), "Heo, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "e"), "Hll, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "E"), "Hll, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "c"), "Hell, O Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "C"), "Hell, O Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "a"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "A"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "d"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "D"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "f"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "F"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "g"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "G"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "i"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "I"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "j"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "J"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "k"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "K"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "m"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "M"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "n"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "N"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "o"), "Hell, cc")
        self.assertEqual(remove_Occ("Hello, Occ", "O"), "Hell, cc")
        self.assertEqual(remove_Occ("Hello, Occ", "p"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "P"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "q"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "Q"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "r"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "R"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "s"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "S"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "t"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "T"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "u"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "U"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "v"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "V"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "w"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "W"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "x"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "X"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "y"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "Y"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "z"), "Hell, Occ")
        self.assertEqual(remove_Occ("Hello, Occ", "Z"), "Hell, Occ")