import unittest
from mbpp_884_code import all_Bits_Set_In_The_Given_Range

class TestAllBitsSetInRange(unittest.TestCase):

    def test_all_Bits_Set_In_The_Given_Range(self):
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 1, 3))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 2, 3))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 3, 2))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 4, 1))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 5, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 6, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 7, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 8, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 9, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 10, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 11, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 12, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 13, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 14, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 15, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 16, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 17, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 18, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 19, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 20, 0))
        self.assertTrue(all_Bits_Set_In_The_Given_Range(15, 0, 4))
        self.assertFalse(all_Bits_Set_In_The_Given_Range(15, 21, 0))
        self.assertTrue(all_Bits_Set_In_The_G