import unittest
from mbpp_973_code import left_rotate

class TestLeftRotate(unittest.TestCase):

    def test_left_rotate(self):
        self.assertEqual(left_rotate("hello", 2), "llohe")
        self.assertEqual(left_rotate("hello", 3), "elloh")
        self.assertEqual(left_rotate("hello", 4), "hello")
        self.assertEqual(left_rotate("hello", 5), "ohell")
        self.assertEqual(left_rotate("hello", 6), "hello")
        self.assertEqual(left_rotate("hello", 7), "helllo")
        self.assertEqual(left_rotate("hello", 8), "lohel")
        self.assertEqual(left_rotate("hello", 9), "hello")
        self.assertEqual(left_rotate("hello", 10), "ohell")
        self.assertEqual(left_rotate("hello", 11), "hello")
        self.assertEqual(left_rotate("hello", 12), "helllo")
        self.assertEqual(left_rotate("hello", 13), "lohel")
        self.assertEqual(left_rotate("hello", 14), "hello")
        self.assertEqual(left_rotate("hello", 15), "ohell")
        self.assertEqual(left_rotate("hello", 16), "hello")
        self.assertEqual(left_rotate("hello", 17), "helllo")
        self.assertEqual(left_rotate("hello", 18), "lohel")
        self.assertEqual(left_rotate("hello", 19), "hello")
        self.assertEqual(left_rotate("hello", 20), "ohell")
        self.assertEqual(left_rotate("hello", 21), "hello")
        self.assertEqual(left_rotate("hello", 22), "helllo")
        self.assertEqual(left_rotate("hello", 23), "lohel")
        self.assertEqual(left_rotate("hello", 24), "hello")
        self.assertEqual(left_rotate("hello", 25), "ohell")
        self.assertEqual(left_rotate("hello", 26), "hello")
        self.assertEqual(left_rotate("hello", 27), "helllo")
        self.assertEqual(left_rotate("hello", 28), "lohel")
        self.assertEqual(left_rotate("hello", 29), "hello")
        self.assertEqual(left_rotate("hello", 30), "ohell")
        self.assertEqual(left_rotate("hello", 31), "hello")
        self.assertEqual(left_rotate("hello", 32), "helllo")
        self.assertEqual(left_rotate("hello", 33), "lohel")
        self.assertEqual(left_rotate("hello", 34), "hello")
        self.assertEqual(left_rotate("hello", 35), "ohell")
        self.assertEqual(left_rotate("hello", 36), "hello")
        self.assertEqual(left_rotate("hello", 37), "helllo")
        self.assertEqual(left_rotate("hello", 38), "lohel")
        self.assertEqual(left_rotate("hello", 39), "hello")
        self.assertEqual(left_rotate("hello", 40), "ohell")
        self.assertEqual(left_rotate("hello", 41), "hello")
        self.assertEqual(left_rotate("hello", 42), "helllo")
        self.assertEqual(left_rotate("hello", 43), "lohel")
        self.assertEqual(left_rotate("hello", 44), "hello")
        self.assertEqual(left_rotate("hello", 45), "ohell")
        self.assertEqual(left_rotate("hello", 46), "hello")
        self.assertEqual(left_rotate("hello", 47), "helllo")
        self.assertEqual(left_rotate("hello", 48), "lohel")
        self.assertEqual(left_rotate("hello", 49), "hello")
        self.assertEqual(left_rotate("hello", 50), "ohell")
        self.assertEqual(left_rotate("hello", 51), "hello")
        self.assertEqual(left_rotate("hello", 52), "helllo")
        self.assertEqual(left_rotate("hello", 53), "lohel")
        self.assertEqual(left_rotate("hello", 54), "hello")
        self.assertEqual(left_rotate("hello", 55), "ohell")
        self.assertEqual(left_rotate("hello", 56), "hello")
        self.assertEqual(left_rotate("hello", 57), "helllo")
        self.assertEqual(left_rotate("hello", 58), "lohel")
        self.assertEqual(left_rotate("hello", 59), "hello")
        self.assertEqual(left_rotate("hello", 60), "ohell")
        self.assertEqual(left_rotate("hello", 61), "hello")
        self.assertEqual(left_rotate("hello", 62), "helllo")
        self.assertEqual(left_rotate("hello", 63), "lohel")
        self.assertEqual(left_rotate("hello", 64), "hello")
        self.assertEqual(left_rotate("hello", 65), "ohell")
        self.assertEqual(left_rotate("hello", 66), "hello")
        self.assertEqual(left_rotate("hello", 67), "helllo")
        self.assertEqual(left_rotate("hello", 68), "lohel")
        self.assertEqual(left_rotate("hello", 69), "hello")
        self.assertEqual