import unittest
from mbpp_799_code import left_Rotate

class TestLeftRotate(unittest.TestCase):

    def test_left_rotate(self):
        self.assertEqual(left_Rotate(1, 2), 1)
        self.assertEqual(left_Rotate(2, 1), 2)
        self.assertEqual(left_Rotate(1, 0), 1)
        self.assertEqual(left_Rotate(2, 3), 1)
        self.assertEqual(left_Rotate(2, 4), 1)
        self.assertEqual(left_Rotate(2, 5), 1)
        self.assertEqual(left_Rotate(2, 6), 2)
        self.assertEqual(left_Rotate(2, 7), 1)
        self.assertEqual(left_Rotate(2, 8), 1)
        self.assertEqual(left_Rotate(2, 9), 1)
        self.assertEqual(left_Rotate(2, 10), 2)
        self.assertEqual(left_Rotate(2, 11), 1)
        self.assertEqual(left_Rotate(2, 12), 1)
        self.assertEqual(left_Rotate(2, 13), 1)
        self.assertEqual(left_Rotate(2, 14), 2)
        self.assertEqual(left_Rotate(2, 15), 1)
        self.assertEqual(left_Rotate(2, 16), 1)
        self.assertEqual(left_Rotate(2, 17), 1)
        self.assertEqual(left_Rotate(2, 18), 2)
        self.assertEqual(left_Rotate(2, 19), 1)
        self.assertEqual(left_Rotate(2, 20), 1)
        self.assertEqual(left_Rotate(2, 21), 1)
        self.assertEqual(left_Rotate(2, 22), 2)
        self.assertEqual(left_Rotate(2, 23), 1)
        self.assertEqual(left_Rotate(2, 24), 1)
        self.assertEqual(left_Rotate(2, 25), 1)
        self.assertEqual(left_Rotate(2, 26), 2)
        self.assertEqual(left_Rotate(2, 27), 1)
        self.assertEqual(left_Rotate(2, 28), 1)
        self.assertEqual(left_Rotate(2, 29), 1)
        self.assertEqual(left_Rotate(2, 30), 2)
        self.assertEqual(left_Rotate(2, 31), 1)
        self.assertEqual(left_Rotate(2, 32), 2)
        self.assertEqual(left_Rotate(2, 33), 1)
        self.assertEqual(left_Rotate(2, 34), 1)
        self.assertEqual(left_Rotate(2, 35), 1)
        self.assertEqual(left_Rotate(2, 36), 2)
        self.assertEqual(left_Rotate(2, 37), 1)
        self.assertEqual(left_Rotate(2, 38), 1)
        self.assertEqual(left_Rotate(2, 39), 1)
        self.assertEqual(left_Rotate(2, 40), 2)
        self.assertEqual(left_Rotate(2, 41), 1)
        self.assertEqual(left_Rotate(2, 42), 1)
        self.assertEqual(left_Rotate(2, 43), 1)
        self.assertEqual(left_Rotate(2, 44), 2)
        self.assertEqual(left_Rotate(2, 45), 1)
        self.assertEqual(left_Rotate(2, 46), 1)
        self.assertEqual(left_Rotate(2, 47), 1)
        self.assertEqual(left_Rotate(2, 48), 2)
        self.assertEqual(left_Rotate(2, 49), 1)
        self.assertEqual(left_Rotate(2, 50), 1)
        self.assertEqual(left_Rotate(2, 51), 1)
        self.assertEqual(left_Rotate(2, 52), 2)
        self.assertEqual(left_Rotate(2, 53), 1)
        self.assertEqual(left_Rotate(2, 54), 1)
        self.assertEqual(left_Rotate(2, 55), 1)
        self.assertEqual(left_Rotate(2, 56), 2)
        self.assertEqual(left_Rotate(2, 57), 1)
        self.assertEqual(left_Rotate(2, 58), 1)
        self.assertEqual(left_Rotate(2, 59), 1)
        self.assertEqual(left_Rotate(2, 60), 2)
        self.assertEqual(left_Rotate(2, 61), 1)
        self.assertEqual(left_Rotate(2, 62), 1)
        self.assertEqual(left_Rotate(2, 63), 1)
        self.assertEqual(left_Rotate(2, 64), 2)
        self.assertEqual(left_Rotate(2, 65), 1)
        self.assertEqual(left_Rotate