import unittest
from mbpp_956_code import split_list

class TestSplitList(unittest.TestCase):

    def test_split_list(self):
        self.assertEqual(split_list("HelloWorld"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123"), ["Hello", "World"])
        self.assertEqual(split_list("Hello123World"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456def"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghi"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghij"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijk"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklm"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnop"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqr"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrs"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrst"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstu"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuv"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabc"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuab"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcde"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdef"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefg"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefgh"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghi"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghij"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijk"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklm"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnop"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqr"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrs"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrst"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstu"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuab"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuabc"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuabcdef"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuabcdefg"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuabcdefgh"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuabcdefghi"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijklnopqrstuabcdefghij"), ["Hello", "World"])
        self.assertEqual(split_list("HelloWorld123abc456defghijklmnopqrstuabcdefghijk