import unittest
from mbpp_495_code import remove_lowercase

class TestRemoveLowercase(unittest.TestCase):

    def test_remove_lowercase(self):
        self.assertEqual(remove_lowercase("Hello World"), "HW")
        self.assertEqual(remove_lowercase("hello world"), "HW")
        self.assertEqual(remove_lowercase("HELLO WORLD"), "HW")
        self.assertEqual(remove_lowercase("123"), "123")
        self.assertEqual(remove_lowercase("abc123"), "123")
        self.assertEqual(remove_lowercase("ABC123"), "123")
        self.assertEqual(remove_lowercase("abcABC123"), "123")
        self.assertEqual(remove_lowercase("ABCabc123"), "123")
        self.assertEqual(remove_lowercase("abcABC123abc"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabc"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("ABCabc123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove_lowercase("abcABC123ABCabcABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC"), "123")
        self.assertEqual(remove