import unittest
from mbpp_776_code import count_vowels

class TestCountVowels(unittest.TestCase):

    def test_count_vowels(self):
        self.assertEqual(count_vowels("hello"), 0)
        self.assertEqual(count_vowels("helloa"), 1)
        self.assertEqual(count_vowels("helloae"), 2)
        self.assertEqual(count_vowels("helloaee"), 3)
        self.assertEqual(count_vowels("helloaeeo"), 4)
        self.assertEqual(count_vowels("helloaeeoou"), 5)
        self.assertEqual(count_vowels("helloaeeoouu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"), 5)
        self.assertEqual(count_vowels("helloaeeoouuuuuuuuuuu