import unittest
from mbpp_36_code import find_Nth_Digit

class TestFindNthDigit(unittest.TestCase):

    def test_find_Nth_Digit(self):
        self.assertEqual(find_Nth_Digit(1, 3, 1), 1)
        self.assertEqual(find_Nth_Digit(2, 3, 1), 2)
        self.assertEqual(find_Nth_Digit(3, 3, 1), 3)
        self.assertEqual(find_Nth_Digit(4, 3, 1), 4)
        self.assertEqual(find_Nth_Digit(5, 3, 1), 5)
        self.assertEqual(find_Nth_Digit(1, 3, 2), 1)
        self.assertEqual(find_Nth_Digit(2, 3, 2), 2)
        self.assertEqual(find_Nth_Digit(3, 3, 2), 3)
        self.assertEqual(find_Nth_Digit(4, 3, 2), 4)
        self.assertEqual(find_Nth_Digit(5, 3, 2), 5)
        self.assertEqual(find_Nth_Digit(1, 3, 3), 1)
        self.assertEqual(find_Nth_Digit(2, 3, 3), 2)
        self.assertEqual(find_Nth_Digit(3, 3, 3), 3)
        self.assertEqual(find_Nth_Digit(4, 3, 3), 4)
        self.assertEqual(find_Nth_Digit(5, 3, 3), 5)
        self.assertEqual(find_Nth_Digit(1, 3, 4), 1)
        self.assertEqual(find_Nth_Digit(2, 3, 4), 2)
        self.assertEqual(find_Nth_Digit(3, 3, 4), 3)
        self.assertEqual(find_Nth_Digit(4, 3, 4), 4)
        self.assertEqual(find_Nth_Digit(5, 3, 4), 5)
        self.assertEqual(find_Nth_Digit(1, 3, 5), 1)
        self.assertEqual(find_Nth_Digit(2, 3, 5), 2)
        self.assertEqual(find_Nth_Digit(3, 3, 5), 3)
        self.assertEqual(find_Nth_Digit(4, 3, 5), 4)
        self.assertEqual(find_Nth_Digit(5, 3, 5), 5)
        self.assertEqual(find_Nth_Digit(1, 4, 1), 1)
        self.assertEqual(find_Nth_Digit(2, 4, 1), 2)
        self.assertEqual(find_Nth_Digit(3, 4, 1), 3)
        self.assertEqual(find_Nth_Digit(4, 4, 1), 4)
        self.assertEqual(find_Nth_Digit(5, 4, 1), 4)
        self.assertEqual(find_Nth_Digit(1, 4, 2), 1)
        self.assertEqual(find_Nth_Digit(2, 4, 2), 2)
        self.assertEqual(find_Nth_Digit(3, 4, 2), 3)
        self.assertEqual(find_Nth_Digit(4, 4, 2), 4)
        self.assertEqual(find_Nth_Digit(5, 4, 2), 4)
        self.assertEqual(find_Nth_Digit(1, 4, 3), 1)
        self.assertEqual(find_Nth_Digit(2, 4, 3), 2)
        self.assertEqual(find_Nth_Digit(3, 4, 3), 3)
        self.assertEqual(find_Nth_Digit(4, 4, 3), 4)
        self.assertEqual(find_Nth_Digit(5, 4, 3), 4)
        self.assertEqual(find_Nth_Digit(1, 4, 4), 1)
        self.assertEqual(find_Nth_Digit(2, 4, 4), 2)
        self.assertEqual(find_Nth_Digit(3, 4, 4), 3)
        self.assertEqual(find_Nth_Digit(4, 4, 4), 4)
        self.assertEqual(find_Nth_Digit(5, 4, 4), 4)
        self.assertEqual(find_Nth_Digit(1, 4, 5), 1)
        self.assertEqual(find_Nth_Digit(2, 4, 5), 2)
        self.assertEqual(find_Nth_Digit(3, 4, 5), 3)
        self.assertEqual(find_Nth_Digit(4, 4, 5), 4)
        self.assertEqual(find_Nth_Digit(