import unittest
from mbpp_407_code import rearrange_bigger

class TestRearrangeBigger(unittest.TestCase):
    def test_simple(self):
        self.assertEqual(rearrange_bigger(123), 321)
        self.assertEqual(rearrange_bigger(456), 546)
        self.assertEqual(rearrange_bigger(789), 987)

    def test_edge(self):
        self.assertFalse(rearrange_bigger(0))
        self.assertFalse(rearrange_bigger(1))
        self.assertFalse(rearrange_bigger(2))
        self.assertFalse(rearrange_bigger(3))
        self.assertFalse(rearrange_bigger(4))
        self.assertFalse(rearrange_bigger(5))
        self.assertFalse(rearrange_bigger(6))
        self.assertFalse(rearrange_bigger(7))
        self.assertFalse(rearrange_bigger(8))
        self.assertFalse(rearrange_bigger(9))
        self.assertFalse(rearrange_bigger(10))
        self.assertFalse(rearrange_bigger(11))
        self.assertFalse(rearrange_bigger(12))
        self.assertFalse(rearrange_bigger(13))
        self.assertFalse(rearrange_bigger(14))
        self.assertFalse(rearrange_bigger(15))
        self.assertFalse(rearrange_bigger(16))
        self.assertFalse(rearrange_bigger(17))
        self.assertFalse(rearrange_bigger(18))
        self.assertFalse(rearrange_bigger(19))
        self.assertFalse(rearrange_bigger(20))
        self.assertFalse(rearrange_bigger(21))
        self.assertFalse(rearrange_bigger(22))
        self.assertFalse(rearrange_bigger(23))
        self.assertFalse(rearrange_bigger(24))
        self.assertFalse(rearrange_bigger(25))
        self.assertFalse(rearrange_bigger(26))
        self.assertFalse(rearrange_bigger(27))
        self.assertFalse(rearrange_bigger(28))
        self.assertFalse(rearrange_bigger(29))
        self.assertFalse(rearrange_bigger(30))
        self.assertFalse(rearrange_bigger(31))
        self.assertFalse(rearrange_bigger(32))
        self.assertFalse(rearrange_bigger(33))
        self.assertFalse(rearrange_bigger(34))
        self.assertFalse(rearrange_bigger(35))
        self.assertFalse(rearrange_bigger(36))
        self.assertFalse(rearrange_bigger(37))
        self.assertFalse(rearrange_bigger(38))
        self.assertFalse(rearrange_bigger(39))
        self.assertFalse(rearrange_bigger(40))
        self.assertFalse(rearrange_bigger(41))
        self.assertFalse(rearrange_bigger(42))
        self.assertFalse(rearrange_bigger(43))
        self.assertFalse(rearrange_bigger(44))
        self.assertFalse(rearrange_bigger(45))
        self.assertFalse(rearrange_bigger(46))
        self.assertFalse(rearrange_bigger(47))
        self.assertFalse(rearrange_bigger(48))
        self.assertFalse(rearrange_bigger(49))
        self.assertFalse(rearrange_bigger(50))
        self.assertFalse(rearrange_bigger(51))
        self.assertFalse(rearrange_bigger(52))
        self.assertFalse(rearrange_bigger(53))
        self.assertFalse(rearrange_bigger(54))
        self.assertFalse(rearrange_bigger(55))
        self.assertFalse(rearrange_bigger(56))
        self.assertFalse(rearrange_bigger(57))
        self.assertFalse(rearrange_bigger(58))
        self.assertFalse(rearrange_bigger(59))
        self.assertFalse(rearrange_bigger(60))
        self.assertFalse(rearrange_bigger(61))
        self.assertFalse(rearrange_bigger(62))
        self.assertFalse(rearrange_bigger(63))
        self.assertFalse(rearrange_bigger(64))
        self.assertFalse(rearrange_bigger(65))
        self.assertFalse(rearrange_bigger(66))
        self.assertFalse(rearrange_bigger(67))
        self.assertFalse(rearrange_bigger(68))
        self.assertFalse(rearrange_bigger(69))
        self.assertFalse(rearrange_bigger(70))
        self.assertFalse(rearrange_bigger(71))
        self.assertFalse(rearrange_bigger(72))
        self.assertFalse(rearrange_bigger(73))
        self.assertFalse(rearrange_bigger(74))
        self.assertFalse(rearrange_bigger(75))
        self.assertFalse(rearrange_bigger(76))
        self.assertFalse(rearrange_bigger(77))
        self.assertFalse(rearrange_bigger(78))
        self.assertFalse(rearrange_bigger(79))
        self.assertFalse(rearrange_bigger(80))
        self.assertFalse(rearrange_bigger(81))
        self.assertFalse(rearrange_bigger(82))
        self.assertFalse(rearrange_bigger(83))
        self.assertFalse(rearrange_bigger(84))
        self.assertFalse(rearrange_bigger(85))