import unittest
from mbpp_396_code import check_char

class TestCheckChar(unittest.TestCase):
    def test_simple_valid(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_simple_invalid(self):
        self.assertEqual(check_char("A"), "Invalid")
    def test_pattern_match(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match2(self):
        self.assertEqual(check_char("aa"), "Invalid")
    def test_pattern_match3(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match4(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match5(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match6(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match7(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match8(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match9(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match10(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match11(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match12(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match13(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match14(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match15(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match16(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match17(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match18(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match19(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match20(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match21(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match22(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match23(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match24(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match25(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match26(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match27(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match28(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match29(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match30(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match31(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match32(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match33(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match34(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match35(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match36(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match37(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match38(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match39(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match40(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match41(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match42(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match43(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match44(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match45(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match46(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match47(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match48(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match49(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match50(self):
        self.assertEqual(check_char("a"), "Valid")
    def test_pattern_match51(self):
        self.assertEqual(check_char("a"), "Valid")
    def