import unittest
from mbpp_224_code import count_Set_Bits

class TestCountSetBits(unittest.TestCase):
    def test_simple_inputs(self):
        self.assertEqual(count_Set_Bits(0), 0)
        self.assertEqual(count_Set_Bits(1), 1)
        self.assertEqual(count_Set_Bits(2), 1)
        self.assertEqual(count_Set_Bits(3), 2)
        self.assertEqual(count_Set_Bits(4), 1)
        self.assertEqual(count_Set_Bits(5), 2)
        self.assertEqual(count_Set_Bits(6), 2)
        self.assertEqual(count_Set_Bits(7), 3)
        self.assertEqual(count_Set_Bits(8), 1)
        self.assertEqual(count_Set_Bits(9), 2)
        self.assertEqual(count_Set_Bits(10), 1)
        self.assertEqual(count_Set_Bits(11), 2)
        self.assertEqual(count_Set_Bits(12), 2)
        self.assertEqual(count_Set_Bits(13), 3)
        self.assertEqual(count_Set_Bits(14), 2)
        self.assertEqual(count_Set_Bits(15), 4)

    def test_edge_and_boundary_conditions(self):
        self.assertEqual(count_Set_Bits(-1), 1)
        self.assertEqual(count_Set_Bits(16), 1)
        self.assertEqual(count_Set_Bits(32), 1)
        self.assertEqual(count_Set_Bits(64), 1)
        self.assertEqual(count_Set_Bits(128), 1)
        self.assertEqual(count_Set_Bits(255), 8)
        self.assertEqual(count_Set_Bits(256), 1)
        self.assertEqual(count_Set_Bits(512), 1)
        self.assertEqual(count_Set_Bits(1024), 1)
        self.assertEqual(count_Set_Bits(2048), 1)
        self.assertEqual(count_Set_Bits(4096), 1)
        self.assertEqual(count_Set_Bits(8192), 1)
        self.assertEqual(count_Set_Bits(16384), 1)
        self.assertEqual(count_Set_Bits(32768), 1)
        self.assertEqual(count_Set_Bits(65536), 1)
        self.assertEqual(count_Set_Bits(131072), 1)
        self.assertEqual(count_Set_Bits(262144), 1)
        self.assertEqual(count_Set_Bits(524288), 1)
        self.assertEqual(count_Set_Bits(1048576), 1)
        self.assertEqual(count_Set_Bits(2097152), 1)
        self.assertEqual(count_Set_Bits(4194304), 1)
        self.assertEqual(count_Set_Bits(8388608), 1)
        self.assertEqual(count_Set_Bits(16777216), 1)
        self.assertEqual(count_Set_Bits(33554432), 1)
        self.assertEqual(count_Set_Bits(67108864), 1)
        self.assertEqual(count_Set_Bits(134217728), 1)
        self.assertEqual(count_Set_Bits(268435456), 1)
        self.assertEqual(count_Set_Bits(536870912), 1)
        self.assertEqual(count_Set_Bits(1073741824), 1)
        self.assertEqual(count_Set_Bits(2147483648), 1)

    def test_complex_and_corner_cases(self):
        self.assertEqual(count_Set_Bits(0x80000000), 1)
        self.assertEqual(count_Set_Bits(0x7fffffff), 31)
        self.assertEqual(count_Set_Bits(0x7fffffff + 1), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 2), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 3), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 4), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 5), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 6), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 7), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 8), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 9), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 10), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 11), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 12), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 13), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 14), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 15), 32)
        self.assertEqual(count_Set_Bits(0x7fffffff + 16), 32)
        self.assertEqual(count_Set_Bits