import unittest
from mbpp_56_code import check

class TestCheckFunction(unittest.TestCase):

    def test_normal_input(self):
        self.assertTrue(check(15))
        self.assertTrue(check(29))
        self.assertTrue(check(96))

    def test_edge_and_boundary_conditions(self):
        self.assertFalse(check(0))
        self.assertFalse(check(1))
        self.assertFalse(check(10))
        self.assertTrue(check(20))
        self.assertTrue(check(99))
        self.assertFalse(check(100))

    def test_negative_numbers(self):
        self.assertFalse(check(-1))
        self.assertFalse(check(-10))
        self.assertFalse(check(-100))

    def test_special_cases(self):
        self.assertFalse(check(2))
        self.assertFalse(check(3))
        self.assertFalse(check(4))
        self.assertFalse(check(5))
        self.assertFalse(check(6))
        self.assertFalse(check(7))
        self.assertFalse(check(8))
        self.assertFalse(check(9))
        self.assertFalse(check(11))
        self.assertFalse(check(13))
        self.assertFalse(check(17))
        self.assertFalse(check(19))
        self.assertFalse(check(21))
        self.assertFalse(check(23))
        self.assertFalse(check(25))
        self.assertFalse(check(27))
        self.assertFalse(check(31))
        self.assertFalse(check(33))
        self.assertFalse(check(35))
        self.assertFalse(check(37))
        self.assertFalse(check(39))
        self.assertFalse(check(41))
        self.assertFalse(check(43))
        self.assertFalse(check(45))
        self.assertFalse(check(47))
        self.assertFalse(check(49))
        self.assertFalse(check(51))
        self.assertFalse(check(53))
        self.assertFalse(check(55))
        self.assertFalse(check(57))
        self.assertFalse(check(59))
        self.assertFalse(check(61))
        self.assertFalse(check(63))
        self.assertFalse(check(65))
        self.assertFalse(check(67))
        self.assertFalse(check(69))
        self.assertFalse(check(71))
        self.assertFalse(check(73))
        self.assertFalse(check(75))
        self.assertFalse(check(77))
        self.assertFalse(check(79))
        self.assertFalse(check(81))
        self.assertFalse(check(83))
        self.assertFalse(check(85))
        self.assertFalse(check(87))
        self.assertFalse(check(89))
        self.assertFalse(check(91))
        self.assertFalse(check(93))
        self.assertFalse(check(95))
        self.assertFalse(check(97))
        self.assertFalse(check(999))
