import unittest
from mbpp_900_code import compile
from nine_hundred_code import match_num

class TestMatchNum(unittest.TestCase):

    def test_normal_input(self):
        self.assertTrue(match_num("5"))
        self.assertTrue(match_num("05"))
        self.assertTrue(match_num("5abc"))

    def test_edge_and_boundary_conditions(self):
        self.assertFalse(match_num("5 "))
        self.assertFalse(match_num("5\n"))
        self.assertFalse(match_num("5\t"))
        self.assertFalse(match_num("5_"))
        self.assertFalse(match_num("5-"))
        self.assertFalse(match_num("5."))
        self.assertFalse(match_num("5,"))
        self.assertFalse(match_num("5;"))
        self.assertFalse(match_num("5!"))
        self.assertFalse(match_num("5@"))
        self.assertFalse(match_num("5#"))
        self.assertFalse(match_num("5$"))
        self.assertFalse(match_num("5%"))
        self.assertFalse(match_num("5^"))
        self.assertFalse(match_num("5&"))
        self.assertFalse(match_num("5*"))
        self.assertFalse(match_num("5("))
        self.assertFalse(match_num("5)"))
        self.assertFalse(match_num("5{"))
        self.assertFalse(match_num("5}"))
        self.assertFalse(match_num("5|"))

    def test_invalid_input(self):
        self.assertFalse(match_num("4"))
        self.assertFalse(match_num("6"))
        self.assertFalse(match_num("7"))
        self.assertFalse(match_num("8"))
        self.assertFalse(match_num("9"))
        self.assertFalse(match_num("0"))
        self.assertFalse(match_num("1"))
        self.assertFalse(match_num("2"))
        self.assertFalse(match_num("3"))
        self.assertFalse(match_num("A"))
        self.assertFalse(match_num("B"))
        self.assertFalse(match_num("C"))
        self.assertFalse(match_num("D"))
        self.assertFalse(match_num("E"))
        self.assertFalse(match_num("F"))
        self.assertFalse(match_num("G"))
        self.assertFalse(match_num("H"))
        self.assertFalse(match_num("I"))
        self.assertFalse(match_num("J"))
        self.assertFalse(match_num("K"))
        self.assertFalse(match_num("L"))
        self.assertFalse(match_num("M"))
        self.assertFalse(match_num("N"))
        self.assertFalse(match_num("O"))
        self.assertFalse(match_num("P"))
        self.assertFalse(match_num("Q"))
        self.assertFalse(match_num("R"))
        self.assertFalse(match_num("S"))
        self.assertFalse(match_num("T"))
        self.assertFalse(match_num("U"))
        self.assertFalse(match_num("V"))
        self.assertFalse(match_num("W"))
        self.assertFalse(match_num("X"))
        self.assertFalse(match_num("Y"))
        self.assertFalse(match_num("Z"))
        self.assertFalse(match_num("_"))
        self.assertFalse(match_num(" "))
        self.assertFalse(match_num(""))
