import unittest
from mbpp_138_code import is_Sum_Of_Powers_Of_Two

class TestIsSumOfPowersOfTwo(unittest.TestCase):
    def test_positive(self):
        self.assertTrue(is_Sum_Of_Powers_Of_Two(0))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(2))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(4))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(6))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(8))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(10))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(14))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(18))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(20))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(26))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(30))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(34))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(38))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(42))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(46))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(50))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(54))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(58))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(62))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(66))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(70))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(74))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(78))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(82))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(86))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(90))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(94))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(98))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(102))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(106))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(110))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(114))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(118))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(122))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(126))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(130))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(134))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(138))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(142))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(146))
        self.assertTrue(is_Sum_Of_Powers_Of_Two(150))
        self.assertTrue(is_Sum_Of_Powers_Of_