import unittest
from mbpp_772_code import remove_length

class TestRemoveLength(unittest.TestCase):

    def test_remove_length(self):
        self.assertEqual(remove_length('Hello World', 5), 'Hello World')
        self.assertEqual(remove_length('Python is awesome', 7), 'Python is awesome')
        self.assertEqual(remove_length('This is a test string', 4), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 0), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 1), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 2), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 3), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 5), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 6), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 7), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 8), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 9), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 10), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 11), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 12), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 13), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 14), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 15), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 16), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 17), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 18), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 19), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 20), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 21), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 22), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 23), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 24), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 25), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 26), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 27), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 28), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 29), 'This is a test string')
        self.assertEqual(remove_length('This is a test string', 30), 'This is a test string')
