import unittest
from mbpp_671_code import set_Right_most_Unset_Bit

class TestSetRightmostUnsetBit(unittest.TestCase):

    def test_set_Right_most_Unset_Bit(self):
        self.assertEqual(set_Right_most_Unset_Bit(0), 1)
        self.assertEqual(set_Right_most_Unset_Bit(1), 2)
        self.assertEqual(set_Right_most_Unset_Bit(2), 2)
        self.assertEqual(set_Right_most_Unset_Bit(3), 3)
        self.assertEqual(set_Right_most_Unset_Bit(4), 4)
        self.assertEqual(set_Right_most_Unset_Bit(5), 5)
        self.assertEqual(set_Right_most_Unset_Bit(6), 6)
        self.assertEqual(set_Right_most_Unset_Bit(7), 7)
        self.assertEqual(set_Right_most_Unset_Bit(8), 8)
        self.assertEqual(set_Right_most_Unset_Bit(9), 9)
        self.assertEqual(set_Right_most_Unset_Bit(10), 10)
        self.assertEqual(set_Right_most_Unset_Bit(11), 11)
        self.assertEqual(set_Right_most_Unset_Bit(12), 12)
        self.assertEqual(set_Right_most_Unset_Bit(13), 13)
        self.assertEqual(set_Right_most_Unset_Bit(14), 14)
        self.assertEqual(set_Right_most_Unset_Bit(15), 15)
        self.assertEqual(set_Right_most_Unset_Bit(16), 16)
        self.assertEqual(set_Right_most_Unset_Bit(17), 17)
        self.assertEqual(set_Right_most_Unset_Bit(18), 18)
        self.assertEqual(set_Right_most_Unset_Bit(19), 19)
        self.assertEqual(set_Right_most_Unset_Bit(20), 20)
        self.assertEqual(set_Right_most_Unset_Bit(21), 21)
        self.assertEqual(set_Right_most_Unset_Bit(22), 22)
        self.assertEqual(set_Right_most_Unset_Bit(23), 23)
        self.assertEqual(set_Right_most_Unset_Bit(24), 24)
        self.assertEqual(set_Right_most_Unset_Bit(25), 25)
        self.assertEqual(set_Right_most_Unset_Bit(26), 26)
        self.assertEqual(set_Right_most_Unset_Bit(27), 27)
        self.assertEqual(set_Right_most_Unset_Bit(28), 28)
        self.assertEqual(set_Right_most_Unset_Bit(29), 29)
        self.assertEqual(set_Right_most_Unset_Bit(30), 30)
        self.assertEqual(set_Right_most_Unset_Bit(31), 31)
        self.assertEqual(set_Right_most_Unset_Bit(32), 32)
        self.assertEqual(set_Right_most_Unset_Bit(33), 33)
        self.assertEqual(set_Right_most_Unset_Bit(34), 34)
        self.assertEqual(set_Right_most_Unset_Bit(35), 35)
        self.assertEqual(set_Right_most_Unset_Bit(36), 36)
        self.assertEqual(set_Right_most_Unset_Bit(37), 37)
        self.assertEqual(set_Right_most_Unset_Bit(38), 38)
        self.assertEqual(set_Right_most_Unset_Bit(39), 39)
        self.assertEqual(set_Right_most_