import unittest
from mbpp_44_code import text_match_string

class TestTextMatchString(unittest.TestCase):

    def test_match_string(self):
        self.assertEqual(text_match_string('HelloWorld'), 'Found a match!')
        self.assertEqual(text_match_string('12345'), 'Found a match!')
        self.assertEqual(text_match_string(''), 'Not matched!')
        self.assertEqual(text_match_string('!@#$%^&*()'), 'Found a match!')
        self.assertEqual(text_match_string(' '), 'Found a match!')
        self.assertEqual(text_match_string('with space'), 'Found a match!')
        self.assertEqual(text_match_string('with_underscore'), 'Found a match!')
        self.assertEqual(text_match_string('with-hyphen'), 'Found a match!')
        self.assertEqual(text_match_string('with.dot'), 'Found a match!')
        self.assertEqual(text_match_string('with:colon'), 'Found a match!')
        self.assertEqual(text_match_string('with;semicolon'), 'Found a match!')
        self.assertEqual(text_match_string('with<less'), 'Found a match!')
        self.assertEqual(text_match_string('with>greater'), 'Found a match!')
        self.assertEqual(text_match_string('with=equals'), 'Found a match!')
        self.assertEqual(text_match_string('with+plus'), 'Found a match!')
        self.assertEqual(text_match_string('with-minus'), 'Found a match!')
        self.assertEqual(text_match_string('with~tilde'), 'Found a match!')
        self.assertEqual(text_match_string('with`backtick'), 'Found a match!')
        self.assertEqual(text_match_string('with{curlybrace}'), 'Found a match!')
        self.assertEqual(text_match_string('with}curlybrace'), 'Found a match!')
        self.assertEqual(text_match_string('with[squarebrace]'), 'Found a match!')
        self.assertEqual(text_match_string('with]squarebrace'), 'Found a match!')
        self.assertEqual(text_match_string('with|vertical'), 'Found a match!')
        self.assertEqual(text_match_string('with\\backslash'), 'Found a match!')
        self.assertEqual(text_match_string('with^circumflex'), 'Found a match!')
        self.assertEqual(text_match_string('with"doublequote'), 'Found a match!')
        self.assertEqual(text_match_string('with\'singlequote'), 'Found a match!')
        self.assertEqual(text_match_string('with*asterisk'), 'Found a match!')
        self.assertEqual(text_match_string('with(paren'), 'Found a match!')
        self.assertEqual(text_match_string('with)paren'), 'Found a match!')
        self.assertEqual(text_match_string('with-underscore'), 'Found a match!')
        self.assertEqual(text_match_string('with:colon'), 'Found a match!')
        self.assertEqual(text_match_string('with;semicolon'), 'Found a match!')
        self.assertEqual(text_match_string('with<less'), 'Found a match!')
        self.assertEqual(text_match_string('with>greater'), 'Found a match!')
        self.assertEqual(text_match_string('with=equals'), 'Found a match!')
        self.assertEqual(text_match_string('with+plus'), 'Found a match!')
        self.assertEqual(text_match_string('with-minus'), 'Found a match!')
        self.assertEqual(text_match_string('with~tilde'), 'Found a match!')
        self.assertEqual(text_match_string('with`backtick'), 'Found a match!')
        self.assertEqual(text_match_string('with{curlybrace}'), 'Found a match!')
        self.assertEqual(text_match_string('with}curlybrace'), 'Found a match!')
        self.assertEqual(text_match_string('with[squarebrace]'), 'Found