import unittest
from mbpp_683_code import sum_Square

class TestSumSquare(unittest.TestCase):

    def test_simple_cases(self):
        self.assertTrue(sum_Square(5))
        self.assertTrue(sum_Square(10))
        self.assertTrue(sum_Square(13))
        self.assertTrue(sum_Square(25))

    def test_edge_conditions(self):
        self.assertFalse(sum_Square(0))
        self.assertFalse(sum_Square(1))
        self.assertFalse(sum_Square(2))
        self.assertFalse(sum_Square(3))
        self.assertFalse(sum_Square(4))
        self.assertFalse(sum_Square(6))
        self.assertFalse(sum_Square(8))
        self.assertFalse(sum_Square(9))
        self.assertFalse(sum_Square(11))
        self.assertFalse(sum_Square(12))
        self.assertFalse(sum_Square(14))
        self.assertFalse(sum_Square(15))
        self.assertFalse(sum_Square(16))
        self.assertFalse(sum_Square(17))
        self.assertFalse(sum_Square(18))
        self.assertFalse(sum_Square(19))
        self.assertFalse(sum_Square(20))
        self.assertFalse(sum_Square(21))
        self.assertFalse(sum_Square(22))
        self.assertFalse(sum_Square(23))
        self.assertFalse(sum_Square(24))
        self.assertFalse(sum_Square(26))
        self.assertFalse(sum_Square(27))
        self.assertFalse(sum_Square(28))
        self.assertFalse(sum_Square(29))
        self.assertFalse(sum_Square(30))
        self.assertFalse(sum_Square(31))
        self.assertFalse(sum_Square(32))
        self.assertFalse(sum_Square(33))
        self.assertFalse(sum_Square(34))
        self.assertFalse(sum_Square(35))
        self.assertFalse(sum_Square(36))
        self.assertFalse(sum_Square(37))
        self.assertFalse(sum_Square(38))
        self.assertFalse(sum_Square(39))
        self.assertFalse(sum_Square(40))
        self.assertFalse(sum_Square(41))
        self.assertFalse(sum_Square(42))
        self.assertFalse(sum_Square(43))
        self.assertFalse(sum_Square(44))
        self.assertFalse(sum_Square(45))
        self.assertFalse(sum_Square(46))
        self.assertFalse(sum_Square(47))
        self.assertFalse(sum_Square(48))
        self.assertFalse(sum_Square(49))
        self.assertFalse(sum_Square(50))
        self.assertFalse(sum_Square(51))
        self.assertFalse(sum_Square(52))
        self.assertFalse(sum_Square(53))
        self.assertFalse(sum_Square(54))
        self.assertFalse(sum_Square(55))
        self.assertFalse(sum_Square(56))
        self.assertFalse(sum_Square(57))
        self.assertFalse(sum_Square(58))
        self.assertFalse(sum_Square(59))
        self.assertFalse(sum_Square(60))
        self.assertFalse(sum_Square(61))
        self.assertFalse(sum_Square(62))
        self.assertFalse(sum_Square(63))
        self.assertFalse(sum_Square(64))
        self.assertFalse(sum_Square(65))
        self.assertFalse(sum_Square(66))
        self.assertFalse(sum_Square(67))
        self.assertFalse(sum_Square(69))
        self.assertFalse(sum_Square(70))
        self.assertFalse(sum_Square(71))
        self.assertFalse(sum_Square(72))
        self.assertFalse(sum_Square(73))
        self.assertFalse(sum_Square(74))
        self.assertFalse(sum_Square(75))
        self.assertFalse(sum_Square(76))
        self.assertFalse(