import unittest
from mbpp_803_code import is_Perfect_Square

class TestIsPerfectSquare(unittest.TestCase):
    def test_simple_inputs(self):
        self.assertTrue(is_Perfect_Square(1))
        self.assertTrue(is_Perfect_Square(4))
        self.assertTrue(is_Perfect_Square(9))
        self.assertTrue(is_Perfect_Square(16))
        self.assertTrue(is_Perfect_Square(25))

    def test_edge_conditions(self):
        self.assertFalse(is_Perfect_Square(0))
        self.assertFalse(is_Perfect_Square(-1))
        self.assertFalse(is_Perfect_Square(2))
        self.assertFalse(is_Perfect_Square(3))
        self.assertFalse(is_Perfect_Square(5))
        self.assertFalse(is_Perfect_Square(7))
        self.assertFalse(is_Perfect_Square(8))
        self.assertFalse(is_Perfect_Square(17))
        self.assertFalse(is_Perfect_Square(100))

    def test_complex_cases(self):
        self.assertTrue(is_Perfect_Square(803))
        self.assertFalse(is_Perfect_Square(804))
        self.assertFalse(is_Perfect_Square(805))
        self.assertFalse(is_Perfect_Square(806))
        self.assertFalse(is_Perfect_Square(807))
        self.assertFalse(is_Perfect_Square(808))
        self.assertFalse(is_Perfect_Square(809))
        self.assertFalse(is_Perfect_Square(810))
        self.assertFalse(is_Perfect_Square(811))
        self.assertFalse(is_Perfect_Square(812))
        self.assertFalse(is_Perfect_Square(813))
        self.assertFalse(is_Perfect_Square(814))
        self.assertFalse(is_Perfect_Square(815))
        self.assertFalse(is_Perfect_Square(816))
        self.assertFalse(is_Perfect_Square(817))
        self.assertFalse(is_Perfect_Square(818))
        self.assertFalse(is_Perfect_Square(819))
        self.assertFalse(is_Perfect_Square(820))
        self.assertFalse(is_Perfect_Square(821))
        self.assertFalse(is_Perfect_Square(822))
        self.assertFalse(is_Perfect_Square(823))
        self.assertFalse(is_Perfect_Square(824))
        self.assertFalse(is_Perfect_Square(825))
        self.assertFalse(is_Perfect_Square(826))
        self.assertFalse(is_Perfect_Square(827))
        self.assertFalse(is_Perfect_Square(828))
        self.assertFalse(is_Perfect_Square(829))
        self.assertFalse(is_Perfect_Square(830))
        self.assertFalse(is_Perfect_Square(831))
        self.assertFalse(is_Perfect_Square(832))
        self.assertFalse(is_Perfect_Square(833))
        self.assertFalse(is_Perfect_Square(834))
        self.assertFalse(is_Perfect_Square(835))
        self.assertFalse(is_Perfect_Square(836))
        self.assertFalse(is_Perfect_Square(837))
        self.assertFalse(is_Perfect_Square(838))
        self.assertFalse(is_Perfect_Square(839))
        self.assertFalse(is_Perfect_Square(840))
        self.assertFalse(is_Perfect_Square(841))
        self.assertFalse(is_Perfect_Square(842))
        self.assertFalse(is_Perfect_Square(843))
        self.assertFalse(is_Perfect_Square(844))
        self.assertFalse(is_Perfect_Square(845))
        self.assertFalse(is_Perfect_Square(846))
        self.assertFalse(is_Perfect_Square(847))
        self.assertFalse(is_Perfect_Square(848))
        self.assertFalse(is_Perfect_Square(849))
        self.assertFalse