import unittest
from mbpp_210_code import is_allowed_specific_char

class TestIsAllowedSpecificChar(unittest.TestCase):
    def test_simple_valid_inputs(self):
        self.assertTrue(is_allowed_specific_char("abc123"))
        self.assertTrue(is_allowed_specific_char("abc123."))

    def test_edge_and_boundary_conditions(self):
        self.assertTrue(is_allowed_specific_char(""))
        self.assertTrue(is_allowed_specific_char("."))
        self.assertTrue(is_allowed_specific_char("a"))
        self.assertTrue(is_allowed_specific_char("1"))
        self.assertTrue(is_allowed_specific_char("0"))
        self.assertTrue(is_allowed_specific_char("a."))
        self.assertTrue(is_allowed_specific_char("123."))

    def test_complex_and_corner_cases(self):
        self.assertFalse(is_allowed_specific_char("a@b"))
        self.assertFalse(is_allowed_specific_char("a#b"))
        self.assertFalse(is_allowed_specific_char("a$b"))
        self.assertFalse(is_allowed_specific_char("a%b"))
        self.assertFalse(is_allowed_specific_char("a^b"))
        self.assertFalse(is_allowed_specific_char("a&b"))
        self.assertFalse(is_allowed_specific_char("a*b"))
        self.assertFalse(is_allowed_specific_char("a(b"))
        self.assertFalse(is_allowed_specific_char("a)b"))
        self.assertFalse(is_allowed_specific_char("a-b"))
        self.assertFalse(is_allowed_specific_char("a+b"))
        self.assertFalse(is_allowed_specific_char("a=b"))
        self.assertFalse(is_allowed_specific_char("a{b"))
        self.assertFalse(is_allowed_specific_char("a}b"))
        self.assertFalse(is_allowed_specific_char("a|b"))
        self.assertFalse(is_allowed_specific_char("a;b"))
        self.assertFalse(is_allowed_specific_char("a:b"))
        self.assertFalse(is_allowed_specific_char("a<b"))
        self.assertFalse(is_allowed_specific_char("a>b"))
        self.assertFalse(is_allowed_specific_char("a?b"))
        self.assertFalse(is_allowed_specific_char("a/b"))
        self.assertFalse(is_allowed_specific_char("a\\b"))
        self.assertFalse(is_allowed_specific_char("a`b"))
        self.assertFalse(is_allowed_specific_char("a~b"))
        self.assertFalse(is_allowed_specific_char("a[b"))
        self.assertFalse(is_allowed_specific_char("a]b"))
        self.assertFalse(is_allowed_specific_char("a'b"))
        self.assertFalse(is_allowed_specific_char("a\"b"))
        self.assertFalse(is_allowed_specific_char("a@b"))
        self.assertFalse(is_allowed_specific_char("a!b"))
        self.assertFalse(is_allowed_specific_char("a#b"))
        self.assertFalse(is_allowed_specific_char("a$b"))
        self.assertFalse(is_allowed_specific_char("a%b"))
        self.assertFalse(is_allowed_specific_char("a^b"))
        self.assertFalse(is_allowed_specific_char("a&b"))
        self.assertFalse(is_allowed_specific_char("a*b"))
        self.assertFalse(is_allowed_specific_char("a(b"))
        self.assertFalse(is_allowed_specific_char("a)b"))
        self.assertFalse(is_allowed_specific_char("a-b"))
        self.assertFalse(is_allowed_specific_char("a+b"))
        self.assertFalse(is_allowed_specific_char("a=b"))
        self.assertFalse(is_allowed_specific_char("a{b"))
        self.assertFalse(is_allowed_specific_char("a}b"))
        self.assertFalse(is_allowed_specific_char("a|b