import unittest
from mbpp_482_code import match

class TestMatchFunction(unittest.TestCase):
    def test_typical_case(self):
        self.assertEqual(match('CapitalizedWord'), 'Yes')
        self.assertEqual(match('lowercasedword'), 'No')
        self.assertEqual(match('CapitalizedWords'), 'No')
        self.assertEqual(match('LowercasedWords'), 'No')
        self.assertEqual(match('Capitalized123'), 'No')
        self.assertEqual(match('Lowercased123'), 'No')

    def test_edge_case(self):
        self.assertEqual(match('CapitalizedWord.'), 'Yes')
        self.assertEqual(match('CapitalizedWord_'), 'Yes')
        self.assertEqual(match('CapitalizedWord-'), 'Yes')
        self.assertEqual(match('CapitalizedWord@'), 'Yes')
        self.assertEqual(match('CapitalizedWord#'), 'Yes')
        self.assertEqual(match('CapitalizedWord$'), 'Yes')
        self.assertEqual(match('CapitalizedWord!'), 'Yes')
        self.assertEqual(match('CapitalizedWord?'), 'Yes')
        self.assertEqual(match('CapitalizedWord,'), 'Yes')
        self.assertEqual(match('CapitalizedWord;'), 'Yes')
        self.assertEqual(match('CapitalizedWord:'), 'Yes')
        self.assertEqual(match('CapitalizedWord[]'), 'Yes')
        self.assertEqual(match('CapitalizedWord{}'), 'Yes')
        self.assertEqual(match('CapitalizedWord()'), 'Yes')
        self.assertEqual(match('CapitalizedWord() '), 'Yes')
        self.assertEqual(match('CapitalizedWord ()'), 'Yes')
        self.assertEqual(match('CapitalizedWord () '), 'Yes')
        self.assertEqual(match('CapitalizedWord\t'), 'Yes')
        self.assertEqual(match('CapitalizedWord\n'), 'Yes')
        self.assertEqual(match('CapitalizedWord\r'), 'Yes')
        self.assertEqual(match('CapitalizedWord\f'), 'Yes')

    def test_corner_case(self):
        self.assertEqual(match(''), 'No')
        self.assertEqual(match(' '), 'No')
        self.assertEqual(match('A'), 'Yes')
        self.assertEqual(match('a'), 'No')
        self.assertEqual(match('Aa'), 'Yes')
        self.assertEqual(match('AaA'), 'Yes')
        self.assertEqual(match('AaAa'), 'Yes')
        self.assertEqual(match('AaAaA'), 'Yes')
        self.assertEqual(match('AaAaAa'), 'Yes')
        self.assertEqual(match('AaAaAaA'), 'Yes')
        self.assertEqual(match('AaAaAaAb'), 'Yes')
        self.assertEqual(match('AaAaAaAbA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAa'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAb'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAb'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbAb'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbAbA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbAbAb'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbAbAbA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbAbAbAb'), 'Yes')
        self.assertEqual(match('AaAaAaAbAaAbAbAbAbAbA'), 'Yes')
        self.assertEqual(match('AaAaAaAbAa