import unittest
from mbpp_598_code import armstrong_number

class TestArmstrongNumber(unittest.TestCase):
    def test_typical_cases(self):
        self.assertTrue(armstrong_number(153))
        self.assertTrue(armstrong_number(370))
        self.assertTrue(armstrong_number(371))
        self.assertTrue(armstrong_number(407))
        self.assertTrue(armstrong_number(1634))
        self.assertTrue(armstrong_number(8208))
        self.assertTrue(armstrong_number(8585))

    def test_edge_and_boundary_cases(self):
        self.assertFalse(armstrong_number(0))
        self.assertFalse(armstrong_number(1))
        self.assertFalse(armstrong_number(2))
        self.assertFalse(armstrong_number(3))
        self.assertFalse(armstrong_number(4))
        self.assertFalse(armstrong_number(5))
        self.assertFalse(armstrong_number(6))
        self.assertFalse(armstrong_number(7))
        self.assertFalse(armstrong_number(8))
        self.assertFalse(armstrong_number(9))
        self.assertFalse(armstrong_number(10))
        self.assertFalse(armstrong_number(11))
        self.assertFalse(armstrong_number(12))
        self.assertFalse(armstrong_number(13))
        self.assertFalse(armstrong_number(14))
        self.assertFalse(armstrong_number(16))
        self.assertFalse(armstrong_number(17))
        self.assertFalse(armstrong_number(18))
        self.assertFalse(armstrong_number(19))
        self.assertFalse(armstrong_number(20))
        self.assertFalse(armstrong_number(21))
        self.assertFalse(armstrong_number(22))
        self.assertFalse(armstrong_number(23))
        self.assertFalse(armstrong_number(24))
        self.assertFalse(armstrong_number(25))
        self.assertFalse(armstrong_number(26))
        self.assertFalse(armstrong_number(27))
        self.assertFalse(armstrong_number(28))
        self.assertFalse(armstrong_number(29))
        self.assertFalse(armstrong_number(30))
        self.assertFalse(armstrong_number(31))
        self.assertFalse(armstrong_number(32))
        self.assertFalse(armstrong_number(33))
        self.assertFalse(armstrong_number(34))
        self.assertFalse(armstrong_number(35))
        self.assertFalse(armstrong_number(36))
        self.assertFalse(armstrong_number(38))
        self.assertFalse(armstrong_number(39))
        self.assertFalse(armstrong_number(40))
        self.assertFalse(armstrong_number(41))
        self.assertFalse(armstrong_number(42))
        self.assertFalse(armstrong_number(43))
        self.assertFalse(armstrong_number(44))
        self.assertFalse(armstrong_number(45))
        self.assertFalse(armstrong_number(46))
        self.assertFalse(armstrong_number(47))
        self.assertFalse(armstrong_number(48))
        self.assertFalse(armstrong_number(49))
        self.assertFalse(armstrong_number(50))
        self.assertFalse(armstrong_number(51))
        self.assertFalse(armstrong_number(52))
        self.assertFalse(armstrong_number(53))
        self.assertFalse(armstrong_number(54))
        self.assertFalse(armstrong_number(55))
        self.assertFalse(armstrong_number(56))
        self.assertFalse(armstrong_number(57))
        self.assertFalse(armstrong_number(58))
        self.assertFalse(armstrong_