import unittest
from mbpp_605_code import prime_num

class TestPrimeNum(unittest.TestCase):

    def test_prime_num_is_prime(self):
        self.assertTrue(prime_num(2))
        self.assertTrue(prime_num(3))
        self.assertTrue(prime_num(5))
        self.assertTrue(prime_num(7))
        self.assertTrue(prime_num(11))
        self.assertTrue(prime_num(13))
        self.assertTrue(prime_num(17))
        self.assertTrue(prime_num(19))
        self.assertTrue(prime_num(23))
        self.assertTrue(prime_num(29))
        self.assertTrue(prime_num(31))
        self.assertTrue(prime_num(37))
        self.assertTrue(prime_num(41))
        self.assertTrue(prime_num(43))
        self.assertTrue(prime_num(47))
        self.assertTrue(prime_num(53))
        self.assertTrue(prime_num(59))
        self.assertTrue(prime_num(61))
        self.assertTrue(prime_num(67))
        self.assertTrue(prime_num(71))
        self.assertTrue(prime_num(73))
        self.assertTrue(prime_num(79))
        self.assertTrue(prime_num(83))
        self.assertTrue(prime_num(89))
        self.assertTrue(prime_num(97))

    def test_prime_num_is_not_prime(self):
        self.assertFalse(prime_num(0))
        self.assertFalse(prime_num(1))
        self.assertFalse(prime_num(4))
        self.assertFalse(prime_num(6))
        self.assertFalse(prime_num(8))
        self.assertFalse(prime_num(9))
        self.assertFalse(prime_num(10))
        self.assertFalse(prime_num(12))
        self.assertFalse(prime_num(14))
        self.assertFalse(prime_num(15))
        self.assertFalse(prime_num(16))
        self.assertFalse(prime_num(18))
        self.assertFalse(prime_num(20))
        self.assertFalse(prime_num(22))
        self.assertFalse(prime_num(24))
        self.assertFalse(prime_num(25))
        self.assertFalse(prime_num(26))
        self.assertFalse(prime_num(28))
        self.assertFalse(prime_num(30))
        self.assertFalse(prime_num(32))
        self.assertFalse(prime_num(33))
        self.assertFalse(prime_num(34))
        self.assertFalse(prime_num(35))
        self.assertFalse(prime_num(36))
        self.assertFalse(prime_num(38))
        self.assertFalse(prime_num(39))
        self.assertFalse(prime_num(40))
        self.assertFalse(prime_num(42))
        self.assertFalse(prime_num(44))
        self.assertFalse(prime_num(45))
        self.assertFalse(prime_num(46))
        self.assertFalse(prime_num(48))
        self.assertFalse(prime_num(49))
        self.assertFalse(prime_num(50))
        self.assertFalse(prime_num(52))
        self.assertFalse(prime_num(54))
        self.assertFalse(prime_num(55))
        self.assertFalse(prime_num(56))
        self.assertFalse(prime_num(58))
        self.assertFalse(prime_num(60))
        self.assertFalse(prime_num(62))
        self.assertFalse(prime_num(63))
        self.assertFalse(prime_num(64))
        self.assertFalse(prime_num(65))
        self.assertFalse(prime_