import unittest
from mbpp_641_code import is_nonagonal

class TestIsNonagonal(unittest.TestCase):
    def test_typical_use_case(self):
        self.assertEqual(is_nonagonal(7), True)
        self.assertEqual(is_nonagonal(12), True)
        self.assertEqual(is_nonagonal(18), True)

    def test_edge_and_boundary_conditions(self):
        self.assertFalse(is_nonagonal(0))
        self.assertFalse(is_nonagonal(1))
        self.assertFalse(is_nonagonal(2))
        self.assertFalse(is_nonagonal(3))
        self.assertFalse(is_nonagonal(4))
        self.assertFalse(is_nonagonal(5))
        self.assertFalse(is_nonagonal(6))
        self.assertTrue(is_nonagonal(8))
        self.assertTrue(is_nonagonal(9))
        self.assertTrue(is_nonagonal(10))
        self.assertTrue(is_nonagonal(11))
        self.assertTrue(is_nonagonal(13))
        self.assertTrue(is_nonagonal(14))
        self.assertTrue(is_nonagonal(15))
        self.assertTrue(is_nonagonal(19))
        self.assertTrue(is_nonagonal(20))
        self.assertTrue(is_nonagonal(21))
        self.assertTrue(is_nonagonal(22))
        self.assertTrue(is_nonagonal(23))
        self.assertTrue(is_nonagonal(27))
        self.assertTrue(is_nonagonal(28))
        self.assertTrue(is_nonagonal(29))
        self.assertTrue(is_nonagonal(30))
        self.assertTrue(is_nonagonal(31))
        self.assertTrue(is_nonagonal(33))
        self.assertTrue(is_nonagonal(34))
        self.assertTrue(is_nonagonal(35))
        self.assertTrue(is_nonagonal(39))
        self.assertTrue(is_nonagonal(40))
        self.assertTrue(is_nonagonal(41))
        self.assertTrue(is_nonagonal(42))
        self.assertTrue(is_nonagonal(43))
        self.assertTrue(is_nonagonal(47))
        self.assertTrue(is_nonagonal(48))
        self.assertTrue(is_nonagonal(49))
        self.assertTrue(is_nonagonal(50))
        self.assertTrue(is_nonagonal(51))
        self.assertTrue(is_nonagonal(53))
        self.assertTrue(is_nonagonal(54))
        self.assertTrue(is_nonagonal(55))
        self.assertTrue(is_nonagonal(59))
        self.assertTrue(is_nonagonal(60))
        self.assertTrue(is_nonagonal(61))
        self.assertTrue(is_nonagonal(62))
        self.assertTrue(is_nonagonal(63))
        self.assertTrue(is_nonagonal(67))
        self.assertTrue(is_nonagonal(68))
        self.assertTrue(is_nonagonal(69))
        self.assertTrue(is_nonagonal(70))
        self.assertTrue(is_nonagonal(71))
        self.assertTrue(is_nonagonal(73))
        self.assertTrue(is_nonagonal(74))
        self.assertTrue(is_nonagonal(75))
        self.assertTrue(is_nonagonal(79))
        self.assertTrue(is_nonagonal(80))
        self.assertTrue(is_nonagonal(81))
        self.assertTrue(is_nonagonal(82))
        self.assertTrue(is_nonagonal(83))
        self.assertTrue(is_nonagonal(87))
        self.assertTrue(is_nonagonal(88))
        self.assertTrue(is_nonagonal(89))
        self.assertTrue(is_nonagonal(90))
        self.assertTrue(is_nonagonal(91))
        self.assertTrue(is_nonagonal(93))
        self.assertTrue(is_nonagonal(94))
        self.assertTrue(