import unittest
from mbpp_18_code import remove_dirty_chars

class TestRemoveDirtyChars(unittest.TestCase):

    def test_remove_dirty_chars(self):
        self.assertEqual(remove_dirty_chars("Hello, World!", "Hello, World!"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "abc"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "xyz"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "Hello"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "World"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "H"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "o"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "W"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "l"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "e"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "r"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "d"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "f"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "c"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "a"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "b"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "g"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "h"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "i"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "j"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "k"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "m"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "n"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "p"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "q"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "r"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "s"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "t"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "u"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "v"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "w"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "x"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "y"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "z"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "A"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "B"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "C"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "D"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "E"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "F"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "G"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "H"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "I"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "J"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "K"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "L"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "M"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "N"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "O"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "P"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "Q"), "Hello, World!")
        self.assertEqual(remove_dirty_chars("Hello, World!", "R"), "Hello, World!")
        self.assertEqual