import unittest
from mbpp_699_code import min_Swaps

class TestMinSwaps(unittest.TestCase):

    def test_min_swaps(self):
        self.assertEqual(min_Swaps("abc", "abc"), 0)
        self.assertEqual(min_Swaps("abc", "def"), 3)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd",), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self.assertEqual(min_Swaps("abc", "abcd"), 1)
        self