import unittest
from mbpp_861_code import anagram_lambda

class TestAnagramLambda(unittest.TestCase):
    def test_anagram_lambda(self):
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "cat"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "dog"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "abc"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "tac"), ["tac", "cat"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "t"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "ct"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "g"), ["god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "a"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "b"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "c"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "d"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "g"), ["god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "o"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "t"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "a"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "b"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "c"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "d"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "g"), ["god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "o"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "t"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "a"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "b"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "c"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "d"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "g"), ["god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "o"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "t"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "a"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "b"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "c"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "d"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "g"), ["god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "o"), ["dog", "god"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "t"), ["cat", "tac"])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "a"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "b"), [])
        self.assertEqual(anagram_lambda(["cat", "dog", "tac", "god"], "c"), ["